### PR TITLE
Add Laravel 5.6 Support

### LINKED ISSUE #71: Laravel 5.6 Support
Please add Laravel 5.6 Support?

### PR DESCRIPTION
**Pull request by irazasyed**
Closes #71

### CODE REVIEW

**Comment by irazasyed** [comment]
Tests failing due to Laravel Manager lacking support for Laravel 5.6. A PR was also created for the same. Ref: https://github.com/GrahamCampbell/Laravel-Manager/pull/11

**Comment by GrahamCampbell** [comment]
In 2 weeks, I am upgrading all of my packages to only support 5.5 and 5.6 and PHP 7.1.3+. In the meanwhile I will not be accepting any PRs.

**Comment by benjamincrozat** [comment]
@irazasyed Thanks for your work by the way... ;-)

**Comment by GrahamCampbell** [comment]
V7.0 has just been released.

**Pull request closed without merging**
