### PR TITLE
Update Installation composer example

### PR DESCRIPTION
**Pull request by ahinkle**
PR adds quotations around the installation notes to specify the version. Using Composer 2.

Screen Shot 2021-01-13 at 8 53 38 PM

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What happens if you delete the quotes around the colons?

**Comment by ahinkle** [comment]
Seen in that screenshot 😉 

```bash
╰─ composer require graham-campbell/github guzzlehttp/guzzle:^7.2 http-interop/http-factory-guzzle:^1.0                                   
zsh: no matches found: guzzlehttp/guzzle:^7.2
```

```bash
╰─ composer require "graham-campbell/github":"^10.0" "guzzlehttp/guzzle":"^7.2" "http-interop/http-factory-guzzle":"^1.0" 
./composer.json has been updated
Running composer update graham-campbell/github guzzlehttp/guzzle http-interop/http-factory-guzzle
Loading composer repositories with package information
Updating dependencies
Lock file operations: 20 installs, 0 updates, 0 removals
  - Locking clue/stream-filter (v1.5.0)
  ...
```

**Comment by ahinkle** [comment]
Ah - Like this?

```bash
╰─ composer require "graham-campbell/github:^10.0" "guzzlehttp/guzzle:^7.2" "http-interop/http-factory-guzzle:^1.0" 
./composer.json has been updated
Running composer update graham-campbell/github guzzlehttp/guzzle http-interop/http-factory-guzzle
Loading composer repositories with package information
Updating dependencies
....
```

It works - I've updated my PR; let me know if you prefer the other way.

**Comment by GrahamCampbell** [comment]
Thanks.

**Pull request merged**
